---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, cvs on gcp, anf, azure netapp files 
summary: Astra Trident 構成で使用できる設定オプションを確認してください。 
---
= ストレージ構成オプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident 構成で使用できる設定オプションを確認してください。



== グローバル構成オプション

以下の設定オプションは、使用するストレージプラットフォームに関係なく、すべての Astra Trident 構成に適用されます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `version`  a| 
構成ファイルのバージョン番号
 a| 
1.



| `storageDriverName`  a| 
ストレージドライバの名前
 a| 
`ontap-nas`、 `ontap-san`、 `ontap-nas-economy`、
`ontap-nas-flexgroup`、 `solidfire-san`、 `azure-netapp-files`または `gcp-cvs`



| `storagePrefix`  a| 
ボリューム名のオプションのプレフィックス。デフォルト：「 netappdvp_」 。
 a| 
ステージング _



| `limitVolumeSize`  a| 
ボリュームサイズに関するオプションの制限。デフォルト：「」（適用されていない）
 a| 
10G

|===

TIP: 使用しないでください `storagePrefix` （デフォルトを含む）をElementバックエンドに使用します。デフォルトでは、が表示されます `solidfire-san` ドライバはこの設定を無視し、プレフィックスを使用しません。Docker ボリュームマッピングには特定の tenantID を使用するか、 Docker バージョン、ドライバ情報、名前の munging が使用されている可能性がある場合には Docker から取得した属性データを使用することを推奨します。

作成するすべてのボリュームでデフォルトのオプションを指定しなくても済むようになっています。。 `size` オプションはすべてのコントローラタイプで使用できます。デフォルトのボリュームサイズの設定方法の例については、 ONTAP の設定に関するセクションを参照してください。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `size`  a| 
新しいボリュームのオプションのデフォルトサイズ。デフォルト：「 1G 」
 a| 
10G

|===


== ONTAP構成

ONTAP を使用する場合は、上記のグローバル構成値に加えて、次のトップレベルオプションを使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `managementLIF`  a| 
ONTAP 管理 LIF の IP アドレス。Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を指定できます。
 a| 
10.0.0.1



| `dataLIF`  a| 
プロトコル LIF の IP アドレス。指定しない場合に生成されます。をクリックします `ontap-nas` ドライバ*のみ*、FQDNを指定できます。この場合、FQDNがNFSマウント処理に使用されます。をクリックします `ontap-san` ドライバのデフォルトでは、SVMのすべてのデータLIF IPが使用され、iSCSIマルチパスが使用されます。IPアドレスの指定 `dataLIF` をクリックします `ontap-san` ドライバは、マルチパスを無効にして、指定されたアドレスだけを使用します。
 a| 
10.0.0.2



| `svm`  a| 
使用する Storage Virtual Machine （管理 LIF がクラスタ LIF である場合は必須）
 a| 
SVM_NFS の場合



| `username`  a| 
ストレージデバイスに接続するユーザ名
 a| 
vsadmin



| `password`  a| 
ストレージ・デバイスに接続するためのパスワード
 a| 
秘密



| `aggregate`  a| 
プロビジョニング用のアグリゲート（オプション。設定する場合は SVM に割り当てる必要があります）。をクリックします `ontap-nas-flexgroup` ドライバ。このオプションは無視されます。SVM に割り当てられたすべてのアグリゲートを使用して FlexGroup ボリュームがプロビジョニングされます。
 a| 
アグリゲート1



| `limitAggregateUsage`  a| 
オプション。使用率がこの割合を超えている場合は、プロビジョニングを失敗させます
 a| 
75%



| `nfsMountOptions`  a| 
NFS マウントオプションのきめ細かな制御。デフォルトは「 -o nfsvers=3 」です。*でのみ使用できます `ontap-nas` および `ontap-nas-economy` ドライバ*。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["ここでは、 NFS ホストの設定情報を参照してください"^]。
 a| 
-o nfsvers=4



| `igroupName`  a| 
プラグインで使用される igroup 。デフォルトは「 netappdvp 」です。* 「 ONTAP-SAN'd river 」のみ利用可能です。
 a| 
myigroup と入力します



| `limitVolumeSize`  a| 
最大要求可能ボリュームサイズと qtree 親ボリュームサイズ。*のため `ontap-nas-economy` また、このオプションを使用すると、作成するFlexVol *のサイズも制限されます。
 a| 
300 g



| `qtreesPerFlexvol`  a| 
FlexVol あたりの最大 qtree 数は [50 、 300] の範囲で指定する必要があります。デフォルトは 200 です。  *のため `ontap-nas-economy` ドライバ。このオプションを使用すると、FlexVol あたりの最大qtree数をカスタマイズできます。
 a| 
300

|===
作成するすべてのボリュームでデフォルトのオプションを指定しなくても済むようになっています。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `spaceReserve`  a| 
スペースリザベーションモード：「 none 」（シンプロビジョニング）または「 volume 」（シック）
 a| 
なし



| `snapshotPolicy`  a| 
使用する Snapshot ポリシー。デフォルトは「 none 」です。
 a| 
なし



| `snapshotReserve`  a| 
Snapshot リザーブの割合。 ONTAP のデフォルトを受け入れる場合は、デフォルトで「」になります
 a| 
10



| `splitOnClone`  a| 
作成時にクローンを親からスプリットします。デフォルトは「 false 」です。
 a| 
いいえ



| `encryption`  a| 
新しいボリュームでNetApp Volume Encryption（NVE）を有効にします。デフォルトはです `false`。このオプションを使用するには、クラスタで NVE のライセンスが設定され、有効になっている必要があります。

NAEがバックエンドで有効になっている場合は、Astra TridentでプロビジョニングされたすべてのボリュームがNAEに有効になります。

詳細については、以下を参照してください。 link:../trident-reco/security-reco.html["Astra TridentとNVEおよびNAEの相互運用性"]。
 a| 
正しいです



| `unixPermissions`  a| 
プロビジョニングされた NFS ボリューム用の NAS オプション。デフォルトは「 777 」
 a| 
777



| `snapshotDir`  a| 
にアクセスするためのNASオプション `.snapshot` ディレクトリ、デフォルトは「false」
 a| 
正しいです



| `exportPolicy`  a| 
NFS エクスポートポリシーで使用する NAS オプション。デフォルトは「 default 」
 a| 
デフォルト



| `securityStyle`  a| 
プロビジョニングされた NFS ボリュームにアクセスするための NAS オプション（デフォルトは「 UNIX 」）
 a| 
混在



| `fileSystemType`  a| 
SAN オプション：ファイルシステムタイプを選択します。デフォルトは「 ext4 」です。
 a| 
XFS



| `tieringPolicy`  a| 
使用する階層化ポリシー。デフォルトは「 none 」です。 ONTAP 9.5 より前の SVM-DR 構成では「 snapshot-only 」です
 a| 
なし

|===


=== スケーリングオプション

。 `ontap-nas` および `ontap-san` ドライバによって、DockerボリュームごとにONTAP FlexVol が作成されます。ONTAP では、クラスタノードあたり最大 1 、 000 個の FlexVol がサポートされます。クラスタの最大 FlexVol 数は 12 、 000 です。この制限内にDockerボリュームの要件が収まる場合は、を参照してください `ontap-nas` FlexVolで提供されるDockerボリューム単位のSnapshotやクローニングなどの機能が追加されているため、NAS解決策 がドライバとして推奨されます。

FlexVol の制限で対応できない数のDockerボリュームが必要な場合は、を選択します `ontap-nas-economy` または `ontap-san-economy` ドライバ。

。 `ontap-nas-economy` ドライバによって、自動管理されるFlexVolのプール内に、DockerボリュームがONTAP qtreeとして作成される。qtree の拡張性は、クラスタノードあたり最大 10 、 000 、クラスタあたり最大 2 、 40 、 000 で、一部の機能を犠牲にすることで大幅に向上しています。。 `ontap-nas-economy` ドライバは、Dockerボリューム単位のスナップショットやクローニングをサポートしていません。


NOTE: 。 `ontap-nas-economy` ドライバは現在Docker Swarmではサポートされていません。Swarmは複数のノード間でのボリューム作成のオーケストレーションを行わないためです。

。 `ontap-san-economy` ドライバによって、自動で管理されるFlexVolの共有プール内にDockerボリュームがONTAP LUNとして作成される。この方法により、各 FlexVol が 1 つの LUN に制限されることはなく、 SAN ワークロードのスケーラビリティが向上します。ストレージアレイに応じて、 ONTAP はクラスタあたり最大 16384 個の LUN をサポートします。このドライバは、ボリュームが下位の LUN であるため、 Docker ボリューム単位の Snapshot とクローニングをサポートします。

を選択します `ontap-nas-flexgroup` 数十億個のファイルを含むペタバイト規模に拡張可能な1つのボリュームへの並列処理能力を高めるドライバ。FlexGroup のユースケースとしては、 AI / ML / DL 、ビッグデータと分析、ソフトウェアのビルド、ストリーミング、ファイルリポジトリなどが考えられます。Trident は、 FlexGroup ボリュームのプロビジョニング時に SVM に割り当てられたすべてのアグリゲートを使用します。Trident での FlexGroup のサポートでは、次の点も考慮する必要があります。

* ONTAP バージョン 9.2 以降が必要です。
* 本ドキュメントの執筆時点では、 FlexGroup は NFS v3 のみをサポートしています。
* SVM で 64 ビットの NFSv3 ID を有効にすることを推奨します。
* 推奨される最小 FlexGroup サイズは 100GB です。
* FlexGroup Volume ではクローニングはサポートされていません。


FlexGroup と FlexGroup に適したワークロードの詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup Volume Best Practices and Implementation Guide"^]。

同じ環境で高度な機能と大規模な拡張性を実現するために、を使用して、Docker Volume Pluginの複数のインスタンスを実行できます `ontap-nas` を使用しています `ontap-nas-economy`。



=== ONTAP 構成ファイルの例

* NFSの例 `ontap-nas` ドライバ*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
* NFSの例 `ontap-nas-flexgroup` ドライバ*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "secret",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
* NFSの例 `ontap-nas-economy` ドライバ*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1"
}
----
* iSCSIの例 `ontap-san` ドライバ*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1",
    "igroupName": "myigroup"
}
----
* NFSの例 `ontap-san-economy` ドライバ*

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "secret",
    "aggregate": "aggr1",
    "igroupName": "myigroup"
}
----


== Element ソフトウェアの設定

Element ソフトウェア（ NetApp HCI / SolidFire ）を使用する場合は、グローバルな設定値のほかに、以下のオプションも使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `Endpoint`  a| 
\https：//<login>：<password>@<mvip>/ JSON -RPC /<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
iSCSI の IP アドレスとポート
 a| 
10.0.0.7 ： 3260



| `TenantName`  a| 
使用する SolidFire テナント（見つからない場合に作成）
 a| 
Docker です



| `InitiatorIFace`  a| 
iSCSI トラフィックをデフォルト以外のインターフェイスに制限する場合は、インターフェイスを指定します
 a| 
デフォルト



| `Types`  a| 
QoS の仕様
 a| 
以下の例を参照してください



| `LegacyNamePrefix`  a| 
アップグレードされた Trident インストールのプレフィックス。1.3.2 より前のバージョンの Trident を使用していて、既存のボリュームをアップグレードする場合は、この値を設定して、ボリューム名メソッドを使用してマッピングされた古いボリュームにアクセスする必要があります。
 a| 
「 netappdvp - 」

|===
。 `solidfire-san` ドライバはDocker Swarmをサポートしていません。



=== Element ソフトウェア構成ファイルの例

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----


== GCP 上の Cloud Volumes Service （ CVS ）構成

Astra Tridentは、デフォルトのCVSサービスタイプがonに設定されたボリュームをサポートしています https://cloud.google.com/architecture/partners/netapp-cloud-volumes/service-types["GCP"^]。Astra Tridentは、CVSサービスタイプで許可されている最小値に関係なく、100GiB未満のCVSボリュームをサポートしていません。したがって、Tridentは要求されたボリュームが最小サイズよりも小さい場合、自動的に100GiBのボリュームを作成します。

GCP で CVS を使用する場合は、グローバル構成の値に加えて、次のオプションも使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `apiRegion`  a| 
CVS アカウントリージョン（必須）。は、このバックエンドがボリュームをプロビジョニングする GCP リージョンです。
 a| 
「 us-west2 」



| `projectNumber`  a| 
GCP プロジェクト番号（必須）。GCP Web ポータルのホーム画面にあります。
 a| 
“ 123456789012 ”



| `hostProjectNumber`  a| 
GCP 共有 VPC ホストプロジェクト番号（共有 VPC を使用する場合は必須）
 a| 
「 098765432109 」



| `apiKey`  a| 
CVS admin ロールを持つ GCP サービスアカウントの API キー（必須）。は、 GCP サービスアカウントの秘密鍵ファイルの JSON 形式のコンテンツです（バックエンド構成ファイルにそのままコピーされます）。サービスアカウントには netappcloudvolumes .admin ロールが必要です。
 a| 
（秘密鍵ファイルの内容）



| `secretKey`  a| 
CVS アカウントのシークレットキー（必須）。CVS Web ポータルの「アカウント設定」 > 「 API アクセス」で確認できます。
 a| 
デフォルト



| `proxyURL`  a| 
CVS アカウントへの接続にプロキシサーバが必要な場合は、プロキシ URL を指定します。プロキシサーバには、 HTTP プロキシまたは HTTPS プロキシを使用できます。HTTPS プロキシの場合、証明書の検証は省略され、プロキシサーバで自己署名証明書が使用されるようになります。* 認証が有効になっているプロキシサーバーはサポートされていません * 。
 a| 
「http://proxy-server-hostname/”



| `nfsMountOptions`  a| 
NFS マウントオプション。デフォルトは「 -o nfsvers=3 」です。
 a| 
「 nfsvers=3 、 proto=tcp 、 timeo=600 」



| `serviceLevel`  a| 
パフォーマンスレベル（標準、プレミアム、エクストリーム）、デフォルトは「標準」
 a| 
Premium サービス



| `network`  a| 
CVS ボリュームに使用される GCP ネットワーク。デフォルトは「 default 」です。
 a| 
デフォルト

|===

NOTE: 共有VPCネットワークを使用する場合は、両方を指定する必要があります `projectNumber` および `hostProjectNumber`。その場合は、 `projectNumber` は、サービスプロジェクトおよびです `hostProjectNumber` は、ホストプロジェクトです。

GCP で CVS を使用している場合は、これらのデフォルトのボリュームオプション設定を使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| `exportRule`  a| 
NFS アクセスリスト（アドレスおよび CIDR サブネット）。デフォルトは「 0.0.0.0/0 」です。
 a| 
「 10.0.1.0/24,10.0.2.100 」



| `snapshotDir`  a| 
の表示/非表示を制御します `.snapshot` ディレクトリ
 a| 
いいえ



| `snapshotReserve`  a| 
スナップショット予約の割合。デフォルトでは、 CVS のデフォルト値である 0 を使用します
 a| 
10.



| `size`  a| 
ボリュームサイズ、デフォルトは「 100GiB 」
 a| 
「10T」

|===


=== GCP 上の CVS 構成ファイルの例

[listing]
----
{
    "version": 1,
    "storageDriverName": "gcp-cvs",
    "projectNumber": "012345678901",
    "apiRegion": "us-west2",
    "apiKey": {
        "type": "service_account",
        "project_id": "my-gcp-project",
        "private_key_id": "<id_value>",
        "private_key": "
        -----BEGIN PRIVATE KEY-----
        <key_value>
        -----END PRIVATE KEY-----\n",
        "client_email": "cloudvolumes-admin-sa@my-gcp-project.iam.gserviceaccount.com",
        "client_id": "123456789012345678901",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40my-gcp-project.iam.gserviceaccount.com"
    },
    "proxyURL": "http://proxy-server-hostname/"
}
----


== Azure NetApp Files 構成

を設定して使用します https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files の特長"^] バックエンドには、次のものが必要です。

* `subscriptionID` Azure NetApp Files を有効にしたAzureサブスクリプションから選択します
* `tenantID`、 `clientID`および `clientSecret` から https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal["アプリケーション登録"^] Azure Active Directory で、 Azure NetApp Files サービスに対する十分な権限がある
* Azure ロケーションに少なくとも 1 つ以上が含まれている https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["委任されたサブネット"^]



TIP: 初めて Azure NetApp Files を使用している場合や、新しい場所で を使用している場合は、そのような初期設定が必要になります https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes?tabs=azure-portal["クイックスタートガイド"^] ご案内します。


NOTE: Astra Trident 21.04.0 以前では、手動 QoS 容量プールはサポートされていません。

[cols="3*"]
|===
| オプション | 説明 | デフォルト 


| `version`  a| 
常に 1
 a| 



| `storageDriverName`  a| 
「 azure-NetApp-files 」
 a| 



| `backendName`  a| 
ストレージバックエンドのカスタム名
 a| 
ドライバ名 + "_" + ランダムな文字



| `subscriptionID`  a| 
Azure サブスクリプションのサブスクリプション ID
 a| 



| `tenantID`  a| 
アプリケーション登録からのテナント ID
 a| 



| `clientID`  a| 
アプリケーション登録からのクライアント ID
 a| 



| `clientSecret`  a| 
アプリケーション登録からのクライアントシークレット
 a| 



| `serviceLevel`  a| 
「 Standard 」、「 Premium 」、「 Ultra 」のいずれか
 a| 
「」（ランダム）



| `location`  a| 
新しいボリュームを作成する Azure の場所の名前をに指定します
 a| 
「」（ランダム）



| `virtualNetwork`  a| 
委任されたサブネットを持つ仮想ネットワークの名前
 a| 
「」（ランダム）



| `subnet`  a| 
に委任されたサブネットの名前 `Microsoft.Netapp/volumes`
 a| 
「」（ランダム）



| `nfsMountOptions`  a| 
NFS マウントオプションのきめ細かな制御
 a| 
「 -o nfsvers=3 」



| `limitVolumeSize`  a| 
要求されたボリュームサイズがこの値を超えている場合、プロビジョニングが失敗します
 a| 
“”（デフォルトでは適用されません）

|===

NOTE: Azure NetApp Files サービスでは、サイズが 100GB 未満のボリュームはサポートされません。Trident では、アプリケーションの導入を容易にするために、より小さいボリュームが要求された場合に、 100GB のボリュームが自動的に作成されます。

これらのオプションを使用して、構成の特別なセクションで各ボリュームをデフォルトでプロビジョニングする方法を制御できます。

[cols="3*"]
|===
| オプション | 説明 | デフォルト 


| `exportRule`  a| 
新しいボリュームのエクスポートルール。CIDR 表記の IPv4 アドレスまたは IPv4 サブネットの任意の組み合わせをカンマで区切って指定する必要があります。
 a| 
「 0.0.0.0/0 」



| `snapshotDir`  a| 
の表示/非表示を制御します `.snapshot` ディレクトリ
 a| 
いいえ



| `size`  a| 
新しいボリュームのデフォルトサイズ
 a| 
「100G」

|===


=== Azure NetApp Files 構成の例

* 例 1 ： azure-NetApp-files* のバックエンドの最小構成

これは、バックエンドの絶対的な最小構成です。この構成では、 Trident がお客様のネットアップアカウント、容量プール、および ANF に委譲されたサブネットをすべて検出し、新しいボリュームをいずれかの場所にランダムに配置します。

この構成は、 ANF の利用を開始して問題を解決するのに役立ちます。 しかし実際には、プロビジョニングするボリュームの範囲を追加して、必要な特性を確実に持ち、それを使用しているコンピューティングに近いネットワーク上で終了するようにします。詳細については、以降の例を参照してください。

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET"
}
----
* 例 2 ： Azure NetApp Files の単一の場所と特定のサービスレベル *

このバックエンド構成では、 Azure の「 eastus 」ロケーションにボリュームを「 Premium 」容量プールに配置します。Trident は、 ANF に委任されているすべてのサブネットを自動的に検出し、いずれかのサブネットに新しいボリュームをランダムに配置します。

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET",
    "location": "eastus",
    "serviceLevel": "Premium"
}
----
* 例 3 ： azure-NetApp-files* の高度な設定

このバックエンド構成は、ボリュームの配置を単一のサブネットにまで適用する手間をさらに削減し、一部のボリュームプロビジョニングのデフォルト設定も変更します。

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET",
    "location": "eastus",
    "serviceLevel": "Premium",
    "virtualNetwork": "my-virtual-network",
    "subnet": "my-subnet",
    "nfsMountOptions": "nfsvers=3,proto=tcp,timeo=600",
    "limitVolumeSize": "500Gi",
    "defaults": {
        "exportRule": "10.0.0.0/24,10.0.1.0/24,10.0.2.100",
        "size": "200Gi"
    }
}
----
* 例 4 ： azure-NetApp-files* を使用する仮想ストレージプール

このバックエンド構成では、複数のが定義され link:../trident-concepts/virtual-storage-pool.html["ストレージのプール"^] 1 つのファイルに格納できます。これは、異なるサービスレベルをサポートする複数の容量プールがあり、それらを表すストレージクラスを Kubernetes で作成する場合に便利です。

仮想ストレージプールの機能の表面に、ラベルが貼られています。

[listing]
----
{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "9f87c765-4774-fake-ae98-a721add45451",
    "tenantID": "68e4f836-edc1-fake-bff9-b2d865ee56cf",
    "clientID": "dd043f63-bf8e-fake-8076-8de91e5713aa",
    "clientSecret": "SECRET",
    "nfsMountOptions": "nfsvers=3,proto=tcp,timeo=600",
    "labels": {
        "cloud": "azure"
    },
    "location": "eastus",

    "storage": [
        {
            "labels": {
                "performance": "gold"
            },
            "serviceLevel": "Ultra"
        },
        {
            "labels": {
                "performance": "silver"
            },
            "serviceLevel": "Premium"
        },
        {
            "labels": {
                "performance": "bronze"
            },
            "serviceLevel": "Standard",
        }
    ]
}
----