---
sidebar: sidebar 
permalink: trident-use/worker-node-prep.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, nfs, iscsi, kubernetes clusters 
summary: Kubernetes クラスタ内のすべてのワーカーノードが、ポッド用にプロビジョニングしたボリュームをマウントできる必要があります。いずれかのバックエンドに ONTAP-NAS 、 ONTAP-NAS-エコノミー 、 ONTAP-NAS-flexgroup ドライバを使用している場合は、ワーカーノードに NFS ツールが必要です。それ以外の場合は iSCSI ツールが必要です。 
---
= ワーカーノードを準備します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Kubernetes クラスタ内のすべてのワーカーノードが、ポッド用にプロビジョニングしたボリュームをマウントできる必要があります。を使用する場合 `ontap-nas`、 `ontap-nas-economy`または `ontap-nas-flexgroup` バックエンドの1つを推進するのに、ワーカーノードにはNFSツールが必要です。それ以外の場合は iSCSI ツールが必要です。

最新バージョンの RedHat CoreOS には、デフォルトで NFS と iSCSI の両方がインストールされています。


WARNING: NFS ツールまたは iSCSI ツールをインストールしたあとは、必ずワーカーノードをリブートしてください。リブートしないと、ボリュームをコンテナに接続できないことがあります。



== ノードサービスの検出

22.07以降、Astra Tridentは、ノードでiSCSIサービスまたはNFSサービスを実行できるかどうかを自動的に検出しようとします。Astra Tridentが、検出されたサービスを特定するためのイベントをノードに対して作成次のイベントを確認するには、コマンドを使用します。

[listing]
----
kubectl get event -A --field-selector involvedObject.name=<Kubernetes node name>
----
Tridentは、TridentノードCRの各ノードで有効になっているサービスも特定します。検出されたサービスを表示するには、次のコマンドを使用します。

[listing]
----
tridentctl get node -o wide -n <Trident namespace>
----

NOTE: ノードサービス検出で検出されたサービスが特定されますが、サービスが適切に設定されていることは保証されませ逆に、検出されたサービスがない場合も、ボリュームのマウントが失敗する保証はありません。



== NFS ボリューム

[cols="3*"]
|===
| プロトコル | オペレーティングシステム | コマンド 


| NFS  a| 
RHEL / CentOS 7.
 a| 
`sudo yum install -y nfs-utils`



| NFS  a| 
Ubuntu
 a| 
`sudo apt-get install -y nfs-common`

|===

NOTE: ブート時に NFS サービスが開始されていることを確認してください。



== iSCSI ボリューム

iSCSI ボリュームを使用するときは、次の点に注意してください。

* Kubernetes クラスタ内の各ノードには一意の IQN を割り当てる必要があります。* これは必須の前提条件です * 。
* RHCOSバージョン4.5以降またはRHEL互換のその他のLinuxディストリビューションをで使用している場合は、を使用します `solidfire-san` DriverおよびElement OS 12.5以前。CHAP認証アルゴリズムがMD5 inに設定されていることを確認します `/etc/iscsi/iscsid.conf`。Element 12.7では、FIPS準拠のセキュアなCHAPアルゴリズムSHA1、SHA-256、およびSHA3-256が提供されています。
+
[listing]
----
sudo sed -i 's/^\(node.session.auth.chap_algs\).*/\1 = MD5/' /etc/iscsi/iscsid.conf
----
* iSCSI PVSを搭載したRHEL / RedHat CoreOSを実行するワーカーノードを使用する場合は、を指定してください `discard` StorageClassのmountOptionを使用して、インラインのスペース再生を実行します。を参照してください https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["RedHat のマニュアル"^]。


[cols="3*"]
|===
| プロトコル | オペレーティングシステム | コマンド 


| iSCSI  a| 
RHEL/CentOS
 a| 
. 次のシステムパッケージをインストールします。
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`

. iscsi-initiator-utils のバージョンが 6.2.0.874-2.el7 以降であることを確認します。
+
`rpm -q iscsi-initiator-utils`

. スキャンを手動に設定：
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. マルチパスを有効化：
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`

+

NOTE: 確認します `etc/multipath.conf` が含まれます `find_multipaths no` の下 `defaults`。

. を確認します `iscsid` および `multipathd` 実行中：
+
`sudo systemctl enable --now iscsid multipathd`

. を有効にして開始します `iscsi`：
+
`sudo systemctl enable --now iscsi`





| iSCSI  a| 
Ubuntu
 a| 
. 次のシステムパッケージをインストールします。
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`

. open-iscsi バージョンが 2.0.874-5ubuntu2.10 以降（ bionic の場合）または 2.0.874-7.1ubuntu6.1 以降（ Focal の場合）であることを確認します。
+
`dpkg -l open-iscsi`

. スキャンを手動に設定：
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. マルチパスを有効化：
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`

+

NOTE: 確認します `etc/multipath.conf` が含まれます `find_multipaths no` の下 `defaults`。

. を確認します `open-iscsi` および `multipath-tools` 有効になっていて実行中：
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`



|===

NOTE: Ubuntu 18.04の場合は、ターゲットポートをで検出する必要があります `iscsiadm` 開始する前に `open-iscsi` iSCSIデーモンを開始します。または、を変更することもできます `iscsi` サービスを開始します `iscsid` 自動的に。
